// Generated by CoffeeScript 2.5.1
(function() {
  var data, fs, ndjson, outputStream, tab_data, transformStream;

  fs = require('fs');

  ndjson = require('ndjson');

  data = require('./cryptos.json');

  tab_data = [];

  Object.keys(data).forEach(function(x) {
    return tab_data.push(data[x]);
  });

  transformStream = ndjson.stringify();

  outputStream = transformStream.pipe(fs.createWriteStream(__dirname + "/data.ndjson"));

  tab_data.forEach(function(x) {
    return transformStream.write(x);
  });

  transformStream.end();

}).call(this);

//# sourceMappingURL=JsonToNDJSON.js.map
